version: "3.8"

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: jobs_db
    ports:
      - "5432:5432"
    restart: unless-stopped